# Generated by Django 3.1.3 on 2020-11-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('url_code', models.CharField(max_length=10)),
            ],
        ),
    ]
